{% set name = "panel-splitjs" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/panel_splitjs-{{ version }}.tar.gz
  sha256: e5038f7cf37b12b72ef52ac44ff53fd8a72bd111a0ffe28afc1b9fac3450604a

build:
  skip: True # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - panel >=1.8.0
    - nodejs 24.*
    - esbuild 0.25.4
    - packaging
    - pip
  run:
    - python
    - panel >=1.8.0
    - bokeh >=3.8.0
    - packaging

test:
  source_files:
    - tests
  imports:
    - panel_splitjs
  commands:
    - pip check
    - pytest -ra -vv --tb=short tests
  requires:
    - pip
    - pytest
    - pytest-asyncio

about:
  home: https://github.com/panel-extensions/panel-splitjs
  summary: A responsive, draggable split panel component for Panel applications, powered by split.js.
  description: |
    A responsive, draggable split panel component for Panel applications, powered by split.js. Includes:
    - Draggable dividers - Resize panels by dragging the divider between them
    - Collapsible panels - Collapse individual panels with toggle buttons
    - Flexible orientation - Support for both horizontal and vertical splits
    - Size constraints - Enforce minimum and maximum panel sizes
    - Snap behavior - Smart snapping to minimum sizes for better UX
    - Customizable sizes - Control initial and expanded panel sizes
    - Multi-panel support - Create layouts with 2+ panels using MultiSplit
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  dev_url: https://github.com/panel-extensions/panel-splitjs
  doc_url: https://github.com/panel-extensions/panel-splitjs

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
  recipe-maintainers:
    - maximlt
    - philippjfr
